import './js/signup-modal';
import './js/login-modal';
import './js/auth';
import './js/trending-markup';
import './js/loader';
import './js/search-film';
import './js/user-options';
import './js/film-modal';
import './js/ua/ua'
